version: '3'
services:
  nodejs:
    build:
      context: ./node-app  # Ruta al directorio de la aplicación Node.js
    ports:
      - "5000:5000"  # Puerto en el que se ejecutará el servidor Node.js
    volumes:
      - ./node-app:/app  # Monta el código fuente de Node.js en el contenedor

  flask:
    build:
      context: ./flask-app  # Ruta al directorio de la aplicación Flask
    ports:
      - "8000:8000"  # Puerto en el que se ejecutará la aplicación Flask
    volumes:
      - ./flask-app:/app  # Monta el código fuente de Flask en el contenedor
